export const personalProjects = [
  {
    title: "Cars Angular Test",
    description: "This is a test project for Armar-TI",
    image: "/images/projects/personal/cars-armarTI.png",
    building: "Armar-TI",
    tags: ["Angular", "TypeScript", "Jasmine", "HTML", "CSS"],
    id: 0,
    visit: "https://cars-project-web-angular-armar-ti.vercel.app/",
    visitShortName: "Armar-TI's Cars Demo",
  },
  {
    title: "Zip Codes App CERRAT",
    description:
      "This is a test project for Centro de Revisión y Rehabilitación Automotriz (CERRAT)",
    image: "/images/projects/personal/logo-cerrat.png",
    building: "CERRAT",
    tags: ["JavaScript", "HTML", "CSS"],
    id: 1,
    visit: "https://cerrat-prueba-codigos-postales.vercel.app/",
    visitShortName: "Zipcodes app Demo",
  },
  {
    title: "Left Rotation Algorithm",
    description:
      "This is a test project for Centro de Revisión y Rehabilitación Automotriz (CERRAT)",
    image: "/images/projects/personal/logo-cerrat.png",
    building: "CERRAT",
    tags: ["JavaScript", "HTML", "CSS"],
    id: 2,
    visit: "https://cerrat-prueba-left-rotation.vercel.app/",
    visitShortName: " Left Rotation Demo",
  },
  {
    title: "Official ESDMX's website",
    description: "This is the official website of ESDMX",
    image: "/images/projects/personal/esdmx-old.webp",
    building: "ESDMX",
    tags: ["JavaScript", "HTML", "CSS"],
    id: 3,
    visit: "https://esdmx-oficial-website-nativo.vercel.app/",
    visitShortName: "ESDMX's website",
  },
  {
    title: "Mors Motors Homework",
    description: "This is a homework for Mariangel",
    image: "/images/projects/personal/morsMotors.png",
    building: "Freelance",
    tags: ["JavaScript", "HTML", "CSS", "SQL", "PHP"],
    id: 4,
    visit: "https://mor-motors-mariangel-venezuela.vercel.app/",
    visitShortName: "Homework Demo",
  },
  {
    title: "Portfolio Native version 1",
    description: "This is my portfolio on Native first version",
    image: "/images/projects/personal/logo-portfolio.png",
    building: " Personal",
    tags: ["JavaScript", "HTML", "CSS"],
    id: 5,
    visit: "https://my-portfoliov1-native-web.vercel.app/",
    visitShortName: "My Portfolio Native v1 demo",
  },
  {
    title: "Portfolio React version 1 ",
    description: "This is my portfolio on React first version",
    image: "/images/projects/personal/logo-portfolio.png",
    building: " Personal",
    tags: ["React", "JSX", "Bootstrap"],
    id: 5,
    visit: "https://my-portfoliov1-react-web.vercel.app/",
    visitShortName: "My Portfolio React v1 demo",
  },
  {
    title: "Portfolio NextJs version 1",
    description: "This is my portfolio on NextJS first version",
    image: "/images/projects/personal/logo-portfolio.png",
    building: " Personal",
    tags: ["NextJs", "React", "Reactstrap", "Styled Components"],
    id: 5,
    visit: "https://my-portfoliov1-web-next-js.vercel.app/",
    visitShortName: "My Portfolio NextJS v1 demo",
  },
];
